name: shazam
description: shazam app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.18
  google_fonts: ^4.0.3
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.jpg
    - assets/img/logo-png.png
    - assets/img/bg_started.jpg

flutter_native_splash:
  color: "#ffffff"
  image: "assets/img/logo.jpg"

flutter_icons:
  image_path_android: "assets/img/logo.jpg"
  image_path_ios: "assets/img/logo.jpg"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/img/logo.jpg"
